import type { Request, Response } from 'express';
import { detectImageType, MAX_FILES_PER_REQUEST } from '../config/uploads';
import { putImage, removeImage, type StoredImage } from '../services/storage';
import { ApiError } from '../utils/ApiError';

/**
 * Accepts image uploads and returns the URLs to store on an item.
 *
 * Files arrive in memory so every one can be verified before it is stored
 * anywhere. Names are generated by the storage layer and never derived from
 * client input, which rules out path traversal and collisions in one step.
 *
 * Where they end up — Cloudinary or this machine's disk — is `services/storage`
 * to decide. Nothing here needs to know, and the validation below is the same
 * either way.
 */
export async function uploadImages(req: Request, res: Response): Promise<void> {
  const files = (req.files as Express.Multer.File[] | undefined) ?? [];

  if (files.length === 0) {
    throw ApiError.badRequest('Choose at least one image to upload');
  }

  if (files.length > MAX_FILES_PER_REQUEST) {
    throw ApiError.badRequest(`You can upload at most ${MAX_FILES_PER_REQUEST} images at a time`);
  }

  const stored: StoredImage[] = [];

  try {
    for (const file of files) {
      const type = detectImageType(file.buffer);
      if (!type) {
        throw ApiError.badRequest(
          `"${file.originalname}" is not a supported image. Use JPEG, PNG, GIF, WebP or AVIF.`,
        );
      }

      stored.push(await putImage(file.buffer, type.ext));
    }
  } catch (error) {
    /* One bad file should not leave the earlier ones orphaned — and now that
       they may be orphaned in someone else's account rather than in a folder
       here, tidying up matters more than it did. */
    await Promise.all(stored.map((image) => removeImage(image.id)));
    throw error;
  }

  res.status(201).json({
    success: true,
    data: stored.map((image) => ({ url: image.url })),
  });
}
