/* GENERATED by scripts/build-tokens.mjs — do not edit.
   Source of truth: design/tokens.json. Run `npm run tokens` after changing it. */

/**
 * Accents for the embeddable badge, which is an SVG served into somebody
 * else's page and so cannot reach Deck's stylesheet.
 *
 * Each carries its own ink: the two blocks sit at opposite ends of the
 * lightness scale, so the text colour is a property of the block, not a
 * constant the renderer can assume.
 */
export const ACCENTS: Record<string, { fill: string; ink: string }> = {
  pop: { fill: '#b8a9fa', ink: '#180f43' },
  deep: { fill: '#180f43', ink: '#b8a9fa' },
  grey: { fill: '#9c9c99', ink: '#111111' },
};

export const DEFAULT_ACCENT = 'pop';
